name: test
on: [push, pull_request]

jobs:
  test:
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Lua
        uses: leafo/gh-actions-lua@v8
        with:
          luaVersion: "5.4"

      - name: Install LuaRocks
        uses: leafo/gh-actions-luarocks@v4
        with:
          luarocksVersion: "3.8.0"
        run: |
          luarocks install luacheck
          luarocks install --deps-only ./rockspecs/*.rockspec

      - name: Lint
        run: luacheck ./precomp.lua ./test/
